services:
  app:
    build:
      context: ../..
      target: development
    env_file:
      - ../env/.development.env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"

  db:
    env_file:
      - ../env/.development.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}

volumes:
  bundle:
