services:
  app:
    build:
      context: ../..
      target: production
    env_file:
      - ../env/.production.env
    ports:
      - "80:3000"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "2"
          memory: 2GB
    restart: always

  db:
    env_file:
      - ../env/.production.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - prod_db_data:/var/lib/postgresql/data

volumes:
  prod_db_data:
